### [기본적인 이미지 다루기]

In [2]:
### 모듈 로딩
import cv2
import numpy as np

[1] 이미지 데이터 로딩 <hr>
- 컬러/회색 이미지 변환 로딩 가능함

In [3]:
file = '../DATA/IMAGE/naeun1.jpg'

In [20]:
### 컬러 이미지 로딩 [기본값]
img_bgr = cv2.imread(file, cv2.IMREAD_COLOR)

### 회색 이미지 로딩 [기본값]
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

In [5]:
### 이미지 데이터 정보확인
print(f'[Color IMAGE]')
print(f'SHAPE : {img_bgr.shape}    DIM : {img_bgr.ndim}차원', end = '     ')
print(f'SHAPE : {img_bgr.dtype}    SIZE : {img_bgr.size}바이트')

### 이미지 데이터 정보확인
print(f'[Gray IMAGE]')
print(f'SHAPE : {img_gray.shape}    DIM : {img_gray.ndim}차원', end = '     ')
print(f'SHAPE : {img_gray.dtype}    SIZE : {img_gray.size}바이트')

[Color IMAGE]
SHAPE : (625, 500, 3)    DIM : 3차원     SHAPE : uint8    SIZE : 937500바이트
[Gray IMAGE]
SHAPE : (625, 500)    DIM : 2차원     SHAPE : uint8    SIZE : 312500바이트


In [10]:
### 이미지 데이터 읽기
if img_bgr is not None:
    cv2.imshow('[COLOR]', img_bgr)  # 이미지 창 띄우기
    cv2.waitKey()  # 이미지 창 제어
    cv2.destroyAllWindows()  # 이미지 창 닫기
else:
    print('No image file!!')

In [14]:
### 이미지 데이터 읽기
if img_bgr is not None:
    cv2.imshow('[COLOR]', img_bgr)
    while True:
        key = cv2.waitKey()
        print(f'key =>> {key} - {hex(key)}')

        if key == 27:
            cv2.destroyAllWindows()
            break
else:
    print('No image fill!!')

key =>> 27 - 0x1b


In [15]:
### 이미지 화면 출력
save_filename = '../DATA/IMAGE/gray_.jpg'
gray_file = cv2.imwrite(save_filename, img_gray)

In [17]:
### 이미지 채널 분리
import time
img_b, img_g, img_r = cv2.split(img_bgr)

cv2.imshow('[Blue Channel]', img_b)
time.sleep(1)
cv2.imshow('[Green Channel]', img_g)
time.sleep(1)
cv2.imshow('[Red Channel]', img_r)

cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
### 이미지 채널 분리

### ndarray 분리
b, g, r = img_bgr[:, :, 0], img_bgr[:, :, 1], img_bgr[:, :, 2]

cv2.imshow('[IMG-R]', b)
time.sleep(1)
cv2.imshow('[IMG-G]', g)
time.sleep(1)
cv2.imshow('[IMG-B]', r)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
### 이미지 채널 병합

img_b, img_g, img_r = cv2.split(img_bgr)
img_rgb = cv2.merge((img_r, img_g, img_b))
cv2.imshow('[RGB IMAGE]', img_rgb)

cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
### 이미지 색 공간 변환

# BGR => HSV
src_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)
planes = cv2.split(src_hsv)

cv2.imshow('[HSV IMG]', src_hsv)

cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
# 이미지 색 공간 변환

# BGR => HSV
src_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(src_hsv)

cv2.imshow('[IMG-H]', h)
time.sleep(1)
cv2.imshow('[IMG-S]', s)
time.sleep(1)
cv2.imshow('[IMG-V]', v)

cv2.waitKey()
cv2.destroyAllWindows()

In [26]:
### 이미지 축소/확대
down_img = cv2.resize(img_bgr, dsize = (30, 30), interpolation = cv2.INTER_AREA)
up_img = cv2.resize(img_bgr, dsize = (0, 0), fx = 1.5, fy = 1.5, interpolation = cv2.INTER_CUBIC)

cv2.imshow('down_img', down_img)
time.sleep(1)
cv2.imshow('up_img', up_img)
time.sleep(1)
cv2.imshow('ORG', img_bgr)

# esc누르거나 x누르면 창 닫음
if cv2.waitKey() or cv2.getWindowProperty('[COLOR]', cv2.WND_PROP_VISIBLE) < 1:
    cv2.destroyAllWindows()

In [75]:
### 도화지 만들기
h, w = 600, 600

img_w = np.full((h, w), 255, dtype = np.uint8)
ret = cv2.imwrite('../DATA/IMAGE/blank.jpg', img_w)

img_k = np.zeros((300, 300), dtype = np.uint8)
img_k.shape, img_k.ndim

((300, 300), 2)

In [76]:
### 화면에 출력
cv2.imshow('BLACK', img_k)
cv2.imshow('WHITE', img_w)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [77]:
### 이미지 데이터에 그림 그리기
cv2.line(img_k, (10, 10), (70, 70), (255, 0, 0))

img_k = cv2.cvtColor(img_k, cv2.COLOR_GRAY2BGR)
img_k

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [78]:
### 화면에 출력

cv2.imshow('BLACK', img_k)
cv2.imshow('WHITE', img_w)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [79]:
### 직선 그리기
img = cv2.imread('../DATA/IMAGE/blank.jpg')

cv2.line(img, (50, 50), (150, 50), (255, 0, 0))  # 파란색 1픽셀 선
cv2.line(img, (50, 50), (150, 50), (0, 255, 0))  # 초록섹 1픽셀 선
cv2.line(img, (50, 50), (150, 50), (0, 0, 255))  # 빨간색 1픽셀 선

# 하늘색(파랑+초록) 10픽셀 선
cv2.line(img, (100, 100), (400, 100), (255, 255, 0), 10)

# 분홍색(파랑+빨강) 10픽셀 선
cv2.line(img, (100, 150), (400, 150), (0, 255, 255), 10)

# 노란색(초록+빨강) 10픽셀 선
cv2.line(img, (100, 200), (400, 200), (255, 0, 255), 10)

# 회색(파랑+초록+빨강) 10픽셀 선
cv2.line(img, (100, 250), (400, 250), (200, 200, 20), 10)

# 검은색 10픽셀 선
cv2.line(img, (100, 300), (400, 300), (0, 0, 0), 10)

# 4연결 선
cv2.line(img, (100, 350), (400, 400), (0, 0, 255), 20, cv2.LINE_4)

# 8연결 선
cv2.line(img, (100, 400), (400, 450), (0, 0, 255), 20, cv2.LINE_8)

# 안티에일리어싱 선
cv2.line(img, (100, 450), (400, 500), (0, 0, 255), 20, cv2.LINE_AA)

# 이미지 전체에 대각선
cv2.line(img, (0, 0), (500, 500), (0, 0, 255))

cv2.imshow('lines', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [80]:
### 사각형 그리기
img = cv2.imread('../DATA/IMAGE/blank.jpg')

cv2.rectangle(img, (50, 50), (150, 150), (255, 0, 0))  # 좌상, 우하 좌표로 사각형 그리기
# 우하, 좌상 좌표로 사각형 그리기
cv2.rectangle(img, (300, 300), (100, 100), (0, 255, 0), 10)
# 우상, 좌하 좌표로 사각형 채워 그리기
cv2.rectangle(img, (450, 200), (200, 450), (0, 0, 255), -1)

cv2.imshow('rectangle', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [81]:
### 다각형 그리기
img = cv2.imread('../DATA/IMAGE/blank.jpg')

# 넘파이 배열로 좌표 생성
pts1 = np.array([[50, 50], [150, 150], [100, 140], [200, 240]], dtype = np.int32)
# 삼각형 좌표
pts2 = np.array([[350, 50], [250, 200], [450, 200]], dtype = np.int32)
# 삼각형 좌표
pts3 = np.array([[150, 300], [50, 450], [250, 450]], dtype = np.int32)
# 5각형 좌표
pts4 = np.array([[350, 250], [450, 350], [400, 450], [300, 450], [250, 350]], dtype = np.int32)

# 다각형 그리기
cv2.polylines(img, [pts1], False, (255, 0, 0))
cv2.polylines(img, [pts2], False, (0, 0, 0), 10)
cv2.polylines(img, [pts3], True, (0, 0, 255), 10)
cv2.polylines(img, [pts4], True, (0, 0, 0))

cv2.imshow('polyline', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [64]:
### 다각형 그리기
img = cv2.imread('../DATA/IMAGE/blank.jpg')

# 원점(150, 150), 반지름 100
cv2.circle(img, (150, 150), 100, (255, 0, 0))
# 원점(300, 150), 반지름 70
cv2.circle(img, (300, 150), 70, (0, 255, 0), 5)
# 원점(450, 150), 반지름 50, 채우기
cv2.circle(img, (150, 150), 50, (0, 0, 255), -1)

# 원점(50, 300), 반지름(50), 회전0, 0도부터 360도 그리기
cv2.ellipse(img, (50, 300), (50, 50), 0, 0, 360, (0, 0, 255))
# 원점(150, 300), 아래 반원 그리기
cv2.ellipse(img, (150, 300), (50, 50), 0, 0, 180, (255, 0, 0))
# 원점(200, 300), 위 반원 그리기
cv2.ellipse(img, (200, 300), (50, 50), 0, 181, 360, (0, 0, 255))

# 원점(50, 425), 반지름(50, 75), 회전 15도
cv2.ellipse(img, (50, 425), (50, 75), 15, 0, 360, (0, 0, 0))
# 원점(200, 425), 반지름(50, 75), 회전 45도
cv2.ellipse(img, (200, 425), (50, 75), 45, 0, 360, (0, 0, 0))

# 원점(300, 425), 홀쭉한 타원 45도 회전 후 아래 반원 그리기
cv2.ellipse(img, (300, 425), (50, 75), 45, 0, 180, (0, 0, 255))
# 원점(400, 425), 홀쭉한 타원 45도 회전 후 위 반원 그리기
cv2.ellipse(img, (400, 425), (50, 75), 45, 181, 360, (255, 0, 0))

cv2.imshow('polyline', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [96]:
### 글씨 그리기
img = cv2.imread('../DATA/IMAGE/blank.jpg')

# sans-serif small
cv2.putText(img, 'Plain', (50, 30), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0))
# sans-serif normal
cv2.putText(img, 'Simplex', (50, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0))
# sans-serif bold
cv2.putText(img, 'Duplex', (50, 110), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 0))
# sans-serif normal X2
cv2.putText(img, 'Simplex', (200, 110), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255))

# serit small
cv2.putText(img, 'Complex Small', (50, 180), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (0, 0, 0))
# serit normal
cv2.putText(img, 'Complex', (50, 220), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 0))
# serit bold
cv2.putText(img, 'Triplex', (50, 260), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0, 0))
# sans-serif normal X2
cv2.putText(img, 'Complex', (200, 260), cv2.FONT_HERSHEY_TRIPLEX, 2, (0, 0, 255))

# hand-writing sans-serif
cv2.putText(img, 'Script Simplex', (50, 330), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (0, 0, 0))
# hand-writing sans-serif
cv2.putText(img, 'Script Simplex', (50, 370), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 1, (0, 0, 0))

# sans-serif + italic
cv2.putText(img, 'Plain Italic', (50, 430), cv2.FONT_HERSHEY_PLAIN | cv2.FONT_ITALIC, 1, (0, 0, 0))
# sans-serif + italic
cv2.putText(img, 'Complex Italic', (50, 470), cv2.FONT_HERSHEY_PLAIN | cv2.FONT_ITALIC, 1, (0, 0, 0))

cv2.imshow('polyline', img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [102]:
frontalface_model = '../DATA/haarcascades/haarcascade_smile.xml'
img_file = '../DATA/IMAGE/naeun1.jpg'

face_detector = cv2.CascadeClassifier(frontalface_model)
print(face_detector)
# retval = cv2.CascadeClassifier.load(frontalface_model)
# retval

# 이미지 데이터 로딩
imgNP = cv2.imread(img_file)

# 이미지에서 정면 얼굴 인식 => [결과] 인식된 얼굴 수 만큼 위치정보 반환
face_detections = face_detector.detectMultiScale(imgNP)
print(f'face_detections result\n{face_detections}')

< cv2.CascadeClassifier 0000024D4C767430>
face_detections result
[[215  24  46  23]
 [193 152  88  44]
 [102 353 106  52]
 [150  88  91  46]
 [155  75 115  57]
 [313 239  63  31]
 [230  98 154  77]
 [328 423 100  50]
 [334 243 129  64]
 [128 548  87  44]
 [143 523  82  41]]


In [103]:
# 인식된 정면 얼굴 ROI 표시
for (x, y, w, h) in face_detections:
    cv2.rectangle(imgNP, (x, y), (x + w, y + h), (0, 255, 0), 2)

# 화면 출력
cv2.imshow('[M]', imgNP)

# 키 입력 및 X버튼에 따른 창 닫기
if cv2.waitKey() or cv2.getWindowProperty('image', cv2.WND_PROP_VISIBLE) < 1:
    cv2.destroyAllWindows()