In [1]:
# 모듈 로딩
import numpy as np

In [2]:
# ndarray 타입 데이터 생성
 
# 0으로 채워진 ndarray 객체 생성
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2, 3), dtype = np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
# 1로 채워진 ndarray 객체 생성
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10, dtype = np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.ones((2, 5), dtype = np.bool_)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
# 랜덤 데이터로 ndarray 객체 생성
np.random.randint(1, 5, (3, 10))

array([[4, 2, 1, 3, 3, 1, 4, 2, 1, 3],
       [1, 1, 1, 3, 4, 3, 1, 1, 4, 3],
       [3, 3, 2, 4, 3, 1, 3, 3, 4, 2]])

In [12]:
# 0<= 범위 < 1
np.random.rand(5)

array([0.23410329, 0.08971871, 0.37996153, 0.31596677, 0.49829054])

In [13]:
np.random.rand(5, 2)

array([[0.87683911, 0.68860497],
       [0.37125131, 0.26994511],
       [0.47541503, 0.94896921],
       [0.03475559, 0.43062193],
       [0.58525144, 0.72100207]])

In [14]:
# 정규분포 난수
np.random.randn(5)

array([ 0.68977459,  0.60012572, -2.04753755, -0.75152408,  0.26642032])

In [16]:
np.random.randn(5, 2, 3)

array([[[ 0.63859091, -3.71299769,  0.09733273],
        [ 0.59672689, -1.23948046,  1.49903926]],

       [[-0.04267297,  0.70145722, -0.1851851 ],
        [ 1.06553964,  0.05793411, -1.25884292]],

       [[ 1.65929735, -1.61177976, -0.95528463],
        [-2.58570835, -1.02680481,  0.4091776 ]],

       [[-0.10159486, -1.91837595, -0.12061641],
        [-0.92171259,  0.3043708 ,  0.53484664]],

       [[ 0.33878107, -0.7862749 , -1.17692593],
        [-1.64033278,  0.48840615,  0.98728742]]])

In [17]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)

array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [18]:
data = np.random.randn(10)
print(data)

np.random.shuffle(data)
print(data)

[-1.58457724 -0.64770677  0.59857517  0.33225003 -1.14747663  0.61866969
 -0.08798693  0.4250724   0.33225315 -1.15681626]
[-1.14747663  0.33225315 -1.58457724  0.61866969 -0.08798693 -0.64770677
 -1.15681626  0.4250724   0.33225003  0.59857517]


In [19]:
data.sum(), data.max(), data.min()

(-2.317743386975293, 0.6186696890268814, -1.5845772351121241)

In [20]:
data.argmax(), data.argmin()

(3, 2)